name: Test
on:
  push: ~
  pull_request: ~

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    name: Calculate Perl Versions
    outputs:
      versions: ${{ steps.perl-versions.outputs.perl-versions }}
    steps:
      - id: perl-versions
        uses: perl-actions/perl-versions@v1
        with:
          since-perl: v5.8
          with-devel: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dist::Zilla
        uses: perl-actions/install-with-cpm@v1
        with:
          install: Dist::Zilla
      - name: Extract authordeps
        id: authordeps
        run: |
          {
            echo 'deps<<..END_DEPS'
            dzil authordeps --missing 
            echo ..END_DEPS
          } >> "$GITHUB_OUTPUT"
      - name: Install authordeps
        uses: perl-actions/install-with-cpm@v1
        with:
          install: ${{ steps.authordeps.outputs.deps }}
      - name: Build
        id: build
        run: |
          DZIL_COLOR=1 dzil build --no-tgz | tee "/tmp/dzil-build.log"
          echo build="$(grep --only-matching 'built in .*' "/tmp/dzil-build.log" | tail -1 | cut -c10-)" >> "$GITHUB_OUTPUT"
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.build }}
          path: ${{ steps.build.outputs.build }}
    outputs:
      name: ${{ steps.build.outputs.build }}

  test:
    needs:
      - perl-versions
      - build

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.versions) }}

    runs-on: ubuntu-latest
    container:
      image: perl:${{ matrix.perl-version }}-buster

    env:
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      PERL_USE_UNSAFE_INC: 0

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.name }}
      - name: Setup local::lib
        run:
          echo "$RUNNER_TEMP/perl5/bin" >> "$GITHUB_PATH"
          echo "PERL5LIB=$RUNNER_TEMP/perl5/lib/perl5:$PERL5LIB" >> "$GITHUB_ENV"
          echo "PERL_MB_OPT=--install_base $RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
          echo "PERL_MM_OPT=INSTALL_BASE=$RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
      - name: Install dependencies
        run: cpanm --installdeps . --with-recommends --with-suggests --notest
      - name: Run Makefile.PL
        run: perl Makefile.PL
      - name: Run the tests
        run: make test
  test-xt:
    needs:
      - perl-versions
      - build

    runs-on: ubuntu-latest
    container:
      image: perl:5.36-buster

    env:
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      PERL_USE_UNSAFE_INC: 0

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.name }}
      - name: Setup local::lib
        run:
          echo "$RUNNER_TEMP/perl5/bin" >> "$GITHUB_PATH"
          echo "PERL5LIB=$RUNNER_TEMP/perl5/lib/perl5:$PERL5LIB" >> "$GITHUB_ENV"
          echo "PERL_MB_OPT=--install_base $RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
          echo "PERL_MM_OPT=INSTALL_BASE=$RUNNER_TEMP/perl5" >> "$GITHUB_ENV"
      - name: Install dependencies
        run: cpanm --installdeps . --with-develop --with-recommends --with-suggests --notest
      - name: Run the xt tests
        run: prove -lr xt/author
